window.addEventListener("load", function(){

// QUESTIONS GET "COMMENTED" OUT AS THEY ARE ANSWERED

// SCORE UPDATES BY "COMMENTING" OLD SCORES AND REVEALS LOOP CODE AS SCORE INCREASES
	// USE A FLOATING SIDEBAR ON RIGHT-HAND SIDE?

});